version: '3'
services:
  redis:
    image: redis:3.2
    volumes:
      - redis:/data
    ports:
      - "6379"
  postgres:
    image: postgres:10.4
    environment:
      POSTGRES_DB: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_USER: superset
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432"
  superset:
    build:
      context: .
    depends_on:
      - postgres
      - redis
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://superset:superset@postgres:5432/superset
      CACHE_REDIS_URL: redis://redis:6379/1
      SECRET_KEY: mysecretkey
      ADMIN_PASSWORD: admin
    volumes:
      - ./config:/etc/superset
      - superset:/var/lib/superset
    ports:
      - "8088:8088"
    entrypoint: /home/superset/superset-init
  worker:
    build:
      context: .
    depends_on:
      - postgres
      - redis
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://superset:superset@postgres:5432/superset
      CACHE_REDIS_URL: redis://redis:6379/1
      CACHE_REDIS_HOST: redis
      SECRET_KEY: mysecretkey
    volumes:
      - ./config:/etc/superset
      - worker:/var/lib/superset
    entrypoint: celery worker --app=superset.tasks.celery_app:app --pool=prefork -Ofair -c 4
volumes:
  postgres:
    external: false
  redis:
    external: false
  superset:
    external: false
  worker:
    external: false
